import archiver from 'archiver';
import { Writable } from 'stream';

/**
 * Build a zip buffer from generated content.
 * @param {string} description - Product description (used for folder name)
 * @param {{ databaseSchema: string, apiEndpoints: string, uiPages: string, projectStructure: string }} generated
 * @returns {Promise<Buffer>}
 */
export function buildZip(description, generated) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const archive = archiver('zip', { zlib: { level: 9 } });
    const collector = new Writable({
      write(chunk, _enc, cb) {
        chunks.push(chunk);
        cb();
      },
    });
    collector.on('finish', () => resolve(Buffer.concat(chunks)));
    archive.on('error', reject);

    archive.pipe(collector);

    const slug = description.slice(0, 30).replace(/[^a-z0-9]/gi, '-').toLowerCase() || 'saas-starter';
    const prefix = `${slug}/`;

    archive.append(generated.databaseSchema || '# No schema generated', { name: `${prefix}prisma/schema.prisma` });
    archive.append(generated.apiEndpoints || '# No endpoints', { name: `${prefix}docs/API_ENDPOINTS.md` });
    archive.append(generated.uiPages || '# No UI pages', { name: `${prefix}docs/UI_PAGES.md` });
    archive.append(generated.projectStructure || '# No structure', { name: `${prefix}docs/PROJECT_STRUCTURE.md` });

    const readme = `# ${description}\n\nGenerated by AI SaaS Starter Kit Generator.\n\nSee docs/ for schema, API endpoints, and UI pages.`;
    archive.append(readme, { name: `${prefix}README.md` });

    archive.finalize();
  });
}
